---
- name: Install InfluxDB
  apt:
    name: influxdb
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Start InfluxDB service
  service:
    name: influxdb
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"
