---
- name: Install Nagios on Ubuntu
  apt:
    name: nagios3
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Enable and start Nagios service (Ubuntu)
  service:
    name: nagios3
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

