---
- hosts: all
  become: true
  tasks:

  - name: update repository index (CentOS)
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"
    become: true

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    become: true

- hosts: elasticsearch
  become: true
  roles:
    - elasticsearch
    - grafana
    - lampstack

- hosts: kibana
  become: true
  roles:
    - kibana
    - nagios

- hosts: logstash
  become: true
  roles:
    - logstash
    - prometheus

- hosts: influxdb
  become: true
  roles:
    - influxdb
