---
- hosts: all
  become: true
  roles:
    - base

- hosts: elasticsearch
  become: true
  roles:
    - elasticsearch
    - grafana
    - lampstack

- hosts: kibana
  become: true
  roles:
    - kibana
    - nagios

- hosts: logstash
  become: true
  roles:
    - logstash
    - prometheus

- hosts: influxdb
  become: true
  roles:
    - influxdb
