---
- name: Add Elasticsearch RPM key (CentOS)
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_distribution == "CentOS"
  become: true

- name: Add Elasticsearch repository (CentOS)
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_distribution == "CentOS"
  become: true

- name: Install Elasticsearch (CentOS)
  yum:
    name: elasticsearch
    state: present
  when: ansible_distribution == "CentOS"
  become: true
